name = "BibtexQuery"
defaultTargets = ["BibtexQuery", "«bibtex-query»"]

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic"
rev = "v4.29.0-rc1"

[[lean_lib]]
name = "BibtexQuery"

[[lean_exe]]
name = "«bibtex-query»"
root = "BibtexQuery.Main"
