name = "BibtexQuery"
defaultTargets = ["BibtexQuery", "«bibtex-query»"]

[[require]]
name = "UnicodeBasic"
git = "https://github.com/TwoFx/lean4-unicode-basic"
rev = "markus/bump-nightly"

[[lean_lib]]
name = "BibtexQuery"

[[lean_exe]]
name = "«bibtex-query»"
root = "BibtexQuery.Main"
